### ISSUE TITLE
Is a graph API the right thing to do?

### ISSUE THREAD

**Issue by larsga** [commons-rdf/commons-rdf#35]
I have a need for an RDF library in several different projects, and really like the idea of a commons-rdf. However, I'm not sure the current proposal provides the functionality that is actually necessary.

How should Java code interact with RDF? The most common case will be via SPARQL. So a common SPARQL client library with a convenient API, support for persistent connections, SSL, basic auth, etc etc, would be a very valuable thing.

Another case will be to parse (or generate RDF). For this, a simple streaming interface would be perfect.

An API for accessing RDF as an object model I have to say I'm deeply skeptical of, for two reasons. The first reason is that it's very rarely a good idea. In the vast majority of cases, your data either is in a database or should be in database. SPARQL is the right answer in these cases. 

The second reason is that I see many people adoping this API approach to RDF even when they obviously should not. The reason seems to be that developers want an API, and given an API that's what they choose. Even when, architecturally, this is crazy. As a point of comparison, it's very rare for people to interact with relation data via interfaces named Database, Relation, Row, etc. But for RDF this has somehow become the norm. Some of the triple store vendors (like Oracle) even boast of supporting the Jena APIs, even though one should under no circumstances use APIs of that kind to work with triples stored in Oracle.

So my fear is that an API like the one currently proposed will not only fail to provide the functionality that is most commonly needed, but also lead developers astray.

I guess this is probably not the most pleasant feedback to receive, but I felt it had to be said. Sorry about that.

**Comment by stain** [comment]
I think the `Graph` concept is useful - not everyone is accessing pre-existing data on a pre-existing SPARQL server. For instance, a light-weight container for annotations might want to expose just a couple of `Graph` instances without exposing the underlying RDF framework. Someone who is generating RDF as a side-product can chuck their triples in a Graph and then pass it to arbitrary RDF framework for serialization or going to a LOD server.

I can see many libraries that would not use `Graph`, but could use the other `RDFTerm`s.

This would be the case for OWLAPI for instance, which has `Ontology` as a core concept rather than a graph. Operations like `Graph.add()` don't make much sense in general there, as you have to serialize the ontology as RDF before you get a graph.

I don't think it should be a requirement for implementors to provide a `Graph` implementation - thus `RDFTermFactory.createGraph()` is optional.

**Comment by stain** [comment]
Moved to https://issues.apache.org/jira/browse/COMMONSRDF-5
