### ISSUE TITLE
Relationship with Apache Commons RDF

### ISSUE THREAD

**Issue by wikier** [commons-rdf/commons-rdf#43]
For those who do not know it, it has been [proposed to Apache Commons Sandbox another project with the same name](http://markmail.org/message/7uawziagi6kgpowc). Besides the confusion this can cause, I'd like to discuss with the community the relationship, and implications, for us.

The approach is completely different in different aspects: it proposed a wrapper implementation instead of commons interface, it's clearly [designed based on personal decisions](http://markmail.org/message/baretvva62bt3u5m) instead of by committee, etc.

Personally I do not feel comfortable with the situation. Since there is not technical threshold there, the proposal to Apache Commons goes against the motivation why this project has been started. It does not bring so much value for the Semantic Web community besides trying to safe a zombie project by getting some pieces out. But the duality, in name and purpose, is not healthy. 

I'd listen the opinion that other people have, specially @afs and @ansell, but also relevant people like @westei and @stain.

**Comment by ansell** [comment]
Just for reference also Sergio, Andy and I have already discussed the issue with Reto on the Clerezza mailing list:

https://mail-archives.apache.org/mod_mbox/clerezza-dev/201412.mbox/%3CCALvhUEXOdPuzTS5kuKyqkJW=pHMqBzJA6XpA4xWkHsx=VaVT8Q@mail.gmail.com%3E

**Comment by stain** [comment]
I think it's about time to give in and move out of Github and go for a joint effort here, and rather take whatever fights are required within the Apache umbrella. We are in danger of being viewed as "the github breakout".

To meet both ends - the effort could be split between the API interfaces and a reference API - to be fair any Apache Commons * thing is generally usable out of the box and not just empty interfaces (e.g.  W3C DOM style)

**Comment by ansell** [comment]
@stain The issue has been complicated in the past by a few corner cases, IMO, where Reto insists that all useful RDF APIs must not have certain features, generally focusing around never giving any user referencable APIs access to blank node identifiers but also in reference to the way Graphs are portrayed and accessed. We could continue to have that discussion under the Apache Commons mailing list but it may just be a continuous cycle there as it has been on the Clerezza mailing list for years in the past.

I don't think we are currently under any threat of being viewed as a breakout, given the number of major players in the JVM RDF scene that have participated, including Reto at some point, from memory.

However, if the general community wants to attempt to move to Apache Commons for a second time, including the compulsory signup to the very busy Apache Commons dev mailing list as the sole source of discussion for the project (which from memory was a sticking point last time), then we could rethink it.

**Comment by stain** [comment]
Given the [earlier discussion](
http://mail-archives.apache.org/mod_mbox/commons-dev/201412.mbox/%3C5495B09F.2030200%40gmail.com%3E)
about the proposed Apache Commons RDF in the sandbox (based on Clerezza
RDF) and https://github.com/commons-rdf/commons-rdf



Could we meet on a middle ground and say that Commons-RDF and Apache
Commons RDF can become the same thing - basically move the first
development out of Github to Apache, as I suggest on
https://github.com/commons-rdf/commons-rdf/issues/43#issuecomment-69832164


It might be that, during the initial phases, this requires a bit more
project support than dev@commons could provide directly - the current
Github set-up is intended to be easy to become involved to for the
implementing entities (specially those outside Apache) so that the
interfaces can involve.

Perhaps adapting the empty commons-rdf git repository that is already
mirrored to https://github.com/apache/commons-rdf - thus one can prove a
very similar interface for "outsiders".


The biggest issue is the "noisy" mailing list dev@commons - this can be a
challenge for such 'new' projects. There should however be enough
committers involved to start Apache RDF (?) as a new project (under
Commons?) with its own mailing lists and not having to go through the
incubator (which could also be an option given the necessary
philosophical/formation discussions of the project).



What is now the goal of github Commons-RDF, building a set of interfaces,
can be one part of Apache Commons RDF, while the implementation adapted
from Clerezza can be a second part, perhaps in a deeper Java package
org.apache.commons.rdf.reference.

The pure interfaces becomes the integration point that other RDF libraries
can implement, while the practical implementations can be a 'probably good
enough for many' starting point - and thus also usable without going for
one of the big triple store providers.

This would also be meaningful since any Apache Commons * is generally
usable out of the box, and not just an empty set of interfaces (e.g.
org.w3c.dom).  I have currently provided a reference "dummy" implementation
for Github commons-rdf at
https://github.com/commons-rdf/commons-rdf/pull/42  (Note to self - respond
to those comments! So much for the github agility..)


There seem to be some philosophical differences - for instance the
submitted sandbox code includes an event system for listening to graph
changes - while clearly not a part of the RDF 1.1 standard, this could be
useful, but is much less likely to be adapted by third-party implementers
like OpenRDF, Apache Jena and Apache Marmotta. Practically this can simply
be moved to a Maven submodule.



That might mean that both parties should adapt - but this should avoid the
big confusion and also help build the interface-bit of Commons RDF and the
implementation bit from the RDF sandbox.




https://github.com/commons-rdf/commons-rdf/blob/master/CONTRIBUTING.md has
always said that

> The work of this project may be contributed to the Apache Software
Foundation at some stage in the future. Contributors may be asked to sign a
Apache Software Grant if and when that happens.
All committers of the Github commons-rdf (so far) are already Apache
committers so this is a no-op beyond changing the file headers at github.



BTW -
http://svn.apache.org/viewvc/commons/sandbox/rdf/trunk/pom.xml?revision=1646331&view=markup

proposes

<groupId>commons-rdf</groupId>
<artifactId>commons-rdf</artifactId>


Should it not be <groupId>org.apache.commons.commons-rdf</groupId> ?

http://uk.maven.org/maven2/org/apache/commons/

**Comment by ansell** [comment]
I am okay with transplanting the current code into apache commons.

On the groupId, the maven best practices have been to use a full groupId for quite a while now so it is a little strange that it happened that way.

https://maven.apache.org/guides/mini/guide-naming-conventions.html

**Comment by afs** [comment]
The Apache commons project pushed back on having a separate mailing list.  This one thing is, for me, the major blockage here.

If there si aviable community around commons-rdf, then we can choose to create an Apache project via teh incubator for this.  I'm not sensing a big overlap of general Apache commons and this community.

**Comment by wikier** [comment]
Personally I do not see Commons RDF with enough entity for being its own Apache TLP... so either we stay where we are or we try to move to Apache Commons. Just remember that when we started this project the initial idea was to move there at some point, just check our [CONTRIBUTING](https://github.com/commons-rdf/commons-rdf/blob/master/CONTRIBUTING.md) file. I'm aware of the issues of being a subproject regarding infrastructure; we solved the issue of using git (some other Apache Commons subproject such math are already moving in that direction), but we haven't solved the issue of communication in a single mailing lists (`dev@commons.a.o`). Everything can be discussed.

Although I do agree with @ansell that we are not in any threat of being viewed as a breakout, given the number of major players in the JVM RDF scene that have participated here. Having another project with a clear overlap does not bring any value, neither for the users or for the developers. Thus my current feeling is that such *collision* is not healthy for the community. So FMPOV we either  converge or one of the project has to give up.

Having said that, I have the following proposal:

* We honestly present the situation to the Apache Commons PMC
* We then propose our API, which was actually designed by committee, as a basis for Apache Commons RDF
* We evolve the current design in the context of Apache Commons Sandbox
* We keep separated the API from the implementations:
    * We keep clear the point that the major RDF Toolkits (Apache Jena and OpenRDF) are the recommended implementations
    * We make an open call for contributing basic implementations to the project. We can adopt the one provided by @stain, and also work with @retog to move the Clerezza-based implementation (aka *Apache Commons Sandbox RDF*) to that API (what seems to be willing to do according the [last lines of this email](https://mail-archives.apache.org/mod_mbox/clerezza-dev/201412.mbox/%3CCALvhUEXOdPuzTS5kuKyqkJW=pHMqBzJA6XpA4xWkHsx=VaVT8Q@mail.gmail.com%3E))
    * Which wee can easily organize in different Maven artifacts
* We ask for having a dedicated dev mailing list, keeping the general style for announcements or things relevant for the whole project

What do you think? Anything else or whatever you'd change on this proposal?

**Comment by retog** [comment]
Hi @wikier, the points you're raising like your claim that "The approach is completely different in different aspects: it proposed a wrapper implementation instead of commons interface, it's clearly designed based on personal decisions instead of by committee, etc." have been discussed in several places. And given that the apache clerezza project (remember a project with its stated first goal of providing "An API modeling the W3C RDF standard without any vendor specific additions. ") has been at apache for 5 years and as I think apache products should arise from discussions at apache I would like to have the discussions there and will not engage in this duplication here.

**Comment by stain** [comment]
I thinks @wikier has summarized it well, here's my :+1:.

We can also try to keep using the same style of working by github issues and pull requests - it is very productive at this stage with discussing code examples and many possible branches. Like a pull request stays open longer, not because it is controversial code, but because the thread around it is all about formalizing how this should be API wise - which is what the project is all about. 

I think this GitGub project is a great example of how to do open development Github style - even committers with write access create pull requests for almost anything, in order to engage the community. That is tricky in Apache infrastructure - replying to commits@ emails is not quite the same as it operates by a "lazy consensus" model which is not appropriate for API design by committee.

@afs has had success with mirroring those from [apache/jena](https://github.com/apache/jena/pulls) to [dev@jena](http://mail-archives.apache.org/mod_mbox/jena-dev/) (but see [example of the poor rending from email back to github](https://github.com/apache/jena/pull/10#issuecomment-61260475)) -- this thus satisfies the "If it is not on the mailing list it didn't happen" -- most likely the noise from this would be enough to trick dev@commons to give us our own list. :-)

**Comment by afs** [comment]
Apache project charters do not set boundaries.

**Comment by britter** [comment]
Hello Commons RDF community,

first of all, I'm speaking for myself an not on behalf of the Apache Commons PMC.

I'm really confused by this whole situation. This is what happend from my POV: the Commons RDF community at one point had the idea of moving to Apache Commons (which in my eyes made sense, given that fact the Apache Commons is a place to share code between Apache projects). You really began pushing things, you even requested a git mirror on behalf of the Apache Commons project from Infra, which now is unused [1]!
Then Commons RDF decided that it didn't what to join Apache Commons anymore, which was okay (at least for me).

Later Reto showed up and wanted to try things out in the Apache Commons Sandbox. This is perfectly okay for us. Every Apache Committer may start new ideas in our sandbox (in fact we lately granted commit access to all of our repositories to all ASF committers [2]). However to actually grow out of the sandbox and become a proper component, there has to be a community around said component. At the moment, I don't see such a community around the Apache Commons Sandbox RDF component. But who knows, maybe there will be such a community one day? Maybe not. We do not force things. We just let people work with the code (inside the sandbox) the way they like. The is no threat to this component at all. We don't have an evil plan to destroy Commons RDF.
The differences regarding how to implement the RDF spec is not of our business. None of the current Apache Commons team know RDF. Who are we to judge which approach is the right one?

I'm copying this message to the Apache Commons mailing list, so that everybody is up to date. If you want to respond, please also copy your response to the dev ML. If the Common ML is to noisy: we're using prefixes on the ML. You just have to define a filter that delete all mail which do not start with [RDF].

I hope we can settle this issue once and for all. Right now it feels like "Apache Commons are the bad guys" and I don't think we deserve this.

Regards,
Benedikt

[1] https://issues.apache.org/jira/browse/INFRA-8068
[2] http://markmail.org/message/q5slpso253joca7n

**Comment by wikier** [comment]
OK, although a bit too early, I'm fine jumping into `dev@commons.a.o` to discuss this in *the apache way*.

**Comment by wikier** [comment]
find my reply at http://markmail.org/message/hsstfspok6hcugc2
I'd recommend that everyone moves this discussion to that mailing list

**Comment by britter** [comment]
We've also started a discussion about separate mailing lists on per component basis: http://markmail.org/message/irfkonyv47bg33ge

**Comment by wikier** [comment]
great, thanks @britter

**Comment by ansell** [comment]
All future discussion about this will be on dev@commons.apache.org (to subscribe send an email to dev-subscribe@commons.apache.org)
