### ISSUE TITLE
Must Triple (re)implement equals/hashCode?

### ISSUE THREAD

**Issue by stain** [commons-rdf/commons-rdf#45]
It seems like a good idea. In #42's GraphImpl I initially implemented the graph using LinkedHashSet, but for this to make sense I had to implement `equals` and `hashCode` in `Triple`, which then logically (for add(IRI, IRI, IRI) to not insert duplicatE) meant I also had to add it to `IRI`, `Literal` and `BlankNode` (!).  Related to #44.

Now if we specify this (by adding abstract methods with javadoc as a hint), then probably we should also specify to which depth two RDFTerms are considered equal. Is this going too far?

See also [my comments on LinkedHashSet](https://github.com/commons-rdf/commons-rdf/pull/42#discussion_r22910016) in #42.

**Comment by ansell** [comment]
It is opening a can of worms in general for BlankNode, but for the others it should be fairly simple.

In terms of BlankNode equality, we could try "false by default if the local scope is different". Ie, two blank nodes should always return false for equality if they don't have the same implementation and local scope, even if toString/etc. would return the same string.

**Comment by ansell** [comment]
On the depth question, the purpose of the API is to provide interconnections between different libraries so it is definitely relevant to define the expectations for the equals/hashCode methods.

**Comment by stain** [comment]
OK, then I'll sketch out a patch, including weasel words in BlankNode.

**Comment by ansell** [comment]
Anything related to BlankNode requires some level of weasel words. The trick is finding the right balance. It may be nice to have an example of what "local scope" means in practice also. Some transaction handling examples would be useful, and we can then open discussion for when the community would expect equals to be true and where it could be false and they would still be able to do what they need.

**Comment by stain** [comment]
Note to self - #42 should now probably also add tests for those equals statements , e.g. IRI.equals() must NOT normalize ../ etc.

**Comment by afs** [comment]
The contract for RDF terms applies to all subtypes.  It's value-based (structural) equality.  Two things are equal if they behave identically for all time.  (RDF terms will have to be immutable in external appearance.) In addition, you can't fall back on `object.equals` because a graph is a set of triples and a triple is a 3-tuple of RDF terms (with further restrictions on each slot) and a graph is a set of triples.

Tuple equality is slot-equality.  There isn't much room for variation of the contract here.

Two blank nodes are `.equals` if they behave the same in all situations.  

The contract should be expressed in those terms, not in implementation terms. Usually, same label, same allocation policy (and that in effect is a global reference) is correct,

**Comment by stain** [comment]
Thanks for the clarifications, @afs -- I am however uncertain if I need to change anything in the pull request for this. Should this perhaps be declared as equals/hashCode under RDFTerm as well?

My `BlankNodeImpl` now is only equal if it's got the same Graph "local scope" and the same local identifier. If there is no local scope (e.g. it's a free-standing Blank Node) then it will be equal to any other BlankNodeImpl that also has no local scope.

When adding a BlankNodeImpl to a Graph I always clone it to set the local scope. The other I clone only if they are not *Impl - and their equals are liberal in that they only check using the methods, and so would be equal to any other implementations of the same type and structural values. 

IRIImpl compares strictly by string, as specified for [IRI equality](http://www.w3.org/TR/rdf11-concepts/#section-IRIs) - thus say two IRIs with case-difference in the hostname would differ, and http://example.com/file.txt would differ from http://example.com/folder/../file.txt

**Comment by afs** [comment]
#47 mixes implementation choices and external contract.  This is wrong:

"Implementations MUST check the local scope, as two BlankNode in different Graphs MUST differ."

The quote from the spec is out of context - the spec is talking about labels in syntax and the java interface is not (see `internalIdentifier()` : internalIdentifier != label)

Graphs can share bnodes for many reasons:
1. A graph may be implemented as the union or intersection of 2 others so a bnode is "in" the union and the component graph.  This may be a copy or computed composition. By normal set semantics, X in A means X is in A union B.
2. You can take a triple out of a graph, put it into another graph, take out again, and put it back in the first and it is the same triple (same = ".equals") - no change in the first set of triples.

I find a useful working model is that whenever a bnode is created, it gets a globally unique, *hidden* ref of some kind.  This ref defines the identity, for example if bnodes are intern'ed it can be a language pointer.  It is *not* the label used in output syntax (at can be but it's look a bit long in all likelihood).

There are other useful implementation possibilties and they may be more sensible for other design reasons but this global internal ref form must work because the spec says "the set of possible blank nodes is arbitrary. RDF makes no reference to any internal structure of blank nodes."  The global unique refs are 1-1 with the set of possible blank nodes.

**Comment by stain** [comment]
ok, @afs, this is getting tricky to formulate in a concise javadoc way :). It might be easier to formulate in a unit test, like you say in number 2. 

But say in that case, you take a triple with a bnode out of the first graph, and `Graph.add` that to the second graph (let's say subject and property are fixed IRIs). Now you search up "that triple" in both graphs - would the Triple from each be required to be `.equal`? Or would the `BlankNode` of that triple be required to be equal only? Or would it only be equal once it's added back again to the same graph?

So I guess from this it should also be possible to use such BlankNodes in `getTriples(s,p,o)` patterns - this should be made explicit there.

So.. "SHOULD check the local scope"? We don't have a good definition of this "local scope" here - 
but I see now it's defined as part of [`BlankNode#internalIdentifier()`](https://github.com/commons-rdf/commons-rdf/blob/master/src/main/java/com/github/commonsrdf/api/BlankNode.java#L55).

my [modified text for "Graph"](https://github.com/stain/commons-rdf/blob/local-scope/src/main/java/com/github/commonsrdf/api/Graph.java#L27) does not cover things like unions and intersections. We need however something about this under equals to ensure nobody does something stupid as making two bnodes with the ntriplesString _:b1 be equal just from that.

Keeping an internal identifier in the BlankNode can be tricky for streaming - say you are streaming directly from an N-Triples parser - in this case you would want to just make it with the same graph and local (N-triples-compatible) identifier. It would make sense for a reference implementation in commons-rdf (such as `dummyiimpl`) to be usable for this - so that one can write neutral parsers without having to create duplicate beans of `dummyimpl`. 

I can however change `BlankNodeImpl` of #42  to do it like you say with a hidden `java.lang.UUID` and ensure this is propagated between graphs. I guess then I can remove the whole idea of the 'Optional<Graph> localScope' -- well it was fun the few hours it lasted!  Or do I need to keep that because two blank nodes in different graphs should differ, even if one has been 'copied' from another?

**Comment by afs** [comment]
Note that to get #2 to work, there might be implicit copies or it might be sharing real objects.  Implementation choice.  Jena shares real objects (graph-level); there are copies when resources are used in different Models to their original creator (Resource contains a model ref).

The streaming case isn't too tricky.  Jena RIOT avoids needing to keep a label->bNode map in the parser run (old parsers did do this - users occassionaly report OOME or GC hell problems with some data).  The implementation is create a large, unique number per parser run (UUID random will do - 122 bits of uniqueness) and mangle the bNode label used with the per-run large number to produce the id.  This way, there is no growing mapping from label used to bNode yet each bNode label is associated with one and only one unique-pre-run Blank node object.  There are various policy objects for different label to bNode schemes including debug ones like "use the in-file label" (not for real use!)

The persistent layers write and read the internal identifier.

This is just one possible implementation approach, driven by scale needs and one set of reports and experiences.  An in-memory direct  "reference" implementation might choose to do something based on simplicity of expression. Choices - always choices.

**Comment by ansell** [comment]
The basic contract for Triple and RDFTerm/etc. equals and hashCode is merged. Can continue to discuss the finer details of the contract through a pull request with suggested changes to the initial wording.

**Comment by afs** [comment]
It has just occured to me that the contract for hashCode needs state what the algorithm is.  A hashCode for an IRI with some iristring from system A needs to be the same as the hashCode for an IRI object with the same iristring.  Because IRI equality is across implementations, hashCode must be (by Java rules).

Related will be blank nodes (:-) -- I'm tending towards being restrictive on the creation of blank nodes but need to think it all through. 

Roughly: system B can't create blank nodes that are ".equals" to one from system A just by some label. It would need private knwoledge of some kind. System A and system B might not be wildly different - two factories from the same implementation code - or they might be completely independent code.

**Comment by stain** [comment]
I think it's OK that objects from different implementations may have different `hashCode`s. This is the case for instance for the DOM API.

It means you can't mix and match such objects in a hashing structure without converting them all to the same implementation.  Pretty much any Java object structure I have worked with havingh multiple implementations falls over if you do the mix and match, say using them interchangeably with a HashMap.

If we force an implementation of `hashCode` (e.g. always use `ntriplesString().hashCode()`) - then that could unnecessarily introduce performance issues (although the impact can be reduced by caching the hash).

On the other hand, if we do manage to decide on that - we can simply provide this under (I know, yet another) default implementations of hashCode.

**Comment by afs** [comment]
This isn't like the DOM in that it is useful to work across graph implementations.

IRI and Literal have .equals contracts because of RDF 1.1.

The hashCode for IRI would be based solely on the IRI string. 

The hashCode for literals would be based solely on the 3 parts (lex, lang, datatype).

I don't see a performance issue (and these are immutable as well) - what do you see?

**Comment by ansell** [comment]
One performance issue may be if the strings are not being kept as UTF-16 sequences in-memory, for any optimisation reasons that one may think of. It may not be computationally cheap to compute the equivalent hashcode for the UTF-16 sequence, if you are transparently compressing them internally to save space, for example, as an open pull request for OWLAPI illustrates:

https://github.com/owlcs/owlapi/pull/318

However, since they are immutable, that computation could be performed once in the constructor and the field stored (at the cost of space in that case).
